server:
  port: 8001
spring:
  application:
    name: mango-admin
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://0.0.0.0:3308/mango?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
  jpa:
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"