server:
  port: 8002
spring:
  application:
    name: mango-backup


#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
##
mango:
  backup:
    datasource:
      host: 0.0.0.0
      userName: root
      password: 123456
      database: mango
      port: 3308
