server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mango:
  backup:
    datasource:
      host: 0.0.0.0
      userName: root
      password: 123456
      database: mango
      port: 3308

management:
  endpoints:
    web:
      exposure:
        include: "*"

